### ISSUE TITLE
Question : timeout

### ISSUE THREAD

**Issue by x4080** [agilord/postgres_pool#12]
Hi, I wondered if timeout should be set as high as possible ? Since in the code, it wont create new connection if timeout is reached ?

```
  /// The maximum duration a connection is kept open.
  /// New sessions won't be scheduled after this limit is reached.
```
Or I misunderstood things ?

Thanks

Edit : maxConnectionAge

**Comment by isoos** [comment]
In my experience, it is healthy to close the connection every now and then. Whether it is hours or days may depend on the setup, but there seems to be very little harm to recreate the DB connections twice a day. It helps to clean up locked resources on both the client and the server side...

**Comment by x4080** [comment]
@isoos Do you mean, close and re open the pool in this case right ? So instead of long maxConnectionAge, better to use smaller maxConnectionAge but close and reopen it ?

**Comment by isoos** [comment]
pool != single connection

You configure the pool to handle connections for you, and once a connection's `maxConnectionAge` is reached, the pool will not use it anymore (close it), and it will open a new one. The point of using the pool is that it is doing it for you, you don't need to close the connection, or the pool (only at the end of the application, when it is shutting down).

**Comment by x4080** [comment]
@isoos sorry for asking more, in the doc said that
/// New sessions won't be scheduled after this limit is reached.

So it will automatically create new connection for expired connection based on maxConnectionAge ? I was confused about the 'New sessions won't be scheduled after this limit is reached'

If so, then I have no worry then.

BTW how to pass pool connection to isolate ? Currently in my api server, I use trick to close the pool connection when exiting (using httpclient command to server). But cannot figure it out how to pass pool connection to isolate, currently in the isolate, I created a new connection (that dont know how to close it :)   )

Thanks for your patience

**Comment by isoos** [comment]
> So it will automatically create new connection for expired connection based on maxConnectionAge ?

Yes, the pool will manage the automatic creation and closing of connections, honoring the configured parameters as closely as it can.

> how to pass pool connection to isolate ? 

You pass the connection config/url to the isolate, and connect from inside the isolate.
The isolate is just a thread, you create the pool in the beginning, you close it when it exists. If the isolate is a http-serving thread, then you first exit from the serving, then close the pool (or just ignore both).

**Comment by x4080** [comment]
> > So it will automatically create new connection for expired connection based on maxConnectionAge ?
> 
> Yes, the pool will manage the automatic creation and closing of connections, honoring the configured parameters as closely as it can.
> 

Cool !

> > how to pass pool connection to isolate ?
> 
> You pass the connection config/url to the isolate, and connect from inside the isolate. The isolate is just a thread, you create the pool in the beginning, you close it when it exists. If the isolate is a http-serving thread, then you first exit from the serving, then close the pool (or just ignore both).

Ok got it. Thanks for everything

Cheers
