### ISSUE TITLE
Provide a way to configure "application_name" to Postgres connections

### ISSUE THREAD

**Issue by davidmartos96** [agilord/postgres_pool#15]
Hello!
I was wondering if there is any way I could set the `application_name` for all the connections that get opened by the pool.
When using the non pool version of postgres I can do  `SET application_name = 'some_name'"`, but when using the pool, I cannot do that application wide.
Setting the application name can help debugging active connections and queries to the database, for example when using `SELECT * FROM pg_stat_activity`

**Comment by isoos** [comment]
We could run it at the beginning of `runTx` without much worry, and maybe also on `run` callbacks... (For both of them we have `sessionId` parameter which could be set for such use.) However with the later it gets shaky on connection reuse, and I'm not sure how to set it to the default value, and we may need to track it somewhere that a reused connection has a value set on it.

I'm a bit behind with other stuff, but if there is a PR related to this (which include tracking and resetting for reused non-transactional session variable), I will merge it.

**Comment by davidmartos96** [comment]
@isoos I was thinking along the lines of setting the application name after the connection has been opened with `conn.open()`.
Wouldn't using it on `run` and `runTx` couple it too much? Using `SET application_name = 'some_name'"` is always an option for the user to run it for a particular query or transaction.
Here is the place I was thinking of:
https://github.com/agilord/postgres_pool/blob/89c5d48908bfda3c98d378c87a5ead9308f857f8/lib/postgres_pool.dart#L483

For the pool, the application_name could be a callback that could use the `connectionId`
`String? applicationNameBuilder(int connectionId)` 

Or even better, if possible, through a parameter to the PostgresConnection. That would also benefit regular `postgres` package. I believe the application_name can be passed via message in the connection protocol.
Here in the Postgres docs, it gets used as an example in a connection URI like 
`postgresql://other@localhost/otherdb?connect_timeout=10&application_name=myapp` 
Link: https://www.postgresql.org/docs/15/libpq-connect.html

Other libraries for postgres in other languages support the application_name parameter in the URI. Like JDBC on Java or psycopg2 on Python

**Comment by davidmartos96** [comment]
So it would be used like this and it would get replaced internally if provided? Yes, that can be nice as well.

`applicationName: "my-app_instance-{{connectionId}}"`

If you are fine with running the the "SET application_name ..." after opening the connection I will try to make a PR.

Adding it to the Postgres connection protocol could be nice as well, but I don't have experience with it to tackle it that way

**Comment by isoos** [comment]
> So it would be used like this and it would get replaced internally if provided?

Yes.

> Adding it to the Postgres connection protocol could be nice as well, but I don't have experience with it to tackle it that way

If this solves your issue, I'm happy to take it here first, and later if somebody wants to optimize it, they can refactor it. Maybe add extra documentation / TODO about it.

(Also: please bump the version and update CHANGELOG following the established patterns)
