### ISSUE TITLE
Cannot be used with the latest version of `postgres`

### ISSUE THREAD

**Issue by craiglabenz** [agilord/postgres_pool#20]
Hello, thank you so much for writing this package! I noticed that `postgres_pool` has fallen a bit behind `postgres`. The latter is now on version `3.0.3`, whereas `postgres_pool`'s pubspec caps its `postgres` dependency at `2.5.0`. I had hoped to bump the version myself, run the tests, and fix any issues - but there do not seem to be any tests.

Do you have plans to continue development on this project? Is this something the community could help you with?

Thanks again so much!

**Comment by isoos** [comment]
`Pool` support is now part of the `postgres` package:
https://pub.dev/documentation/postgres/latest/postgres/Pool-class.html

I think I'll mark `postgres_pool` as discontinued, as related development will happen only on `package:postgres`. Were you relying on any specific feature that may be missing from `package:postgres` v3's `Pool`?

**Comment by craiglabenz** [comment]
Thanks for the update - I didn't realize connection pooling support had been moved to the main `postgres` package 🎉
