### ISSUE TITLE
timeZone in postgres package defaults to UTC and I can't change to my timezone in the settings of PgPoolSettings

### ISSUE THREAD

**Issue by eduardotd** [agilord/postgres_pool#4]
Good day,

Is there a way to change the timezone or to make the connection to use the database server default timezone?

Thanks in advance,

Cheers

**Comment by isoos** [comment]
@eduardotd Currently there is no such way, but I'm open to accept such change as a PR. `PgPoolSettings` and the `_open` method needs to be updated for that.

**Comment by eduardotd** [comment]
Thanks for the reply!

PR: https://github.com/agilord/postgres_pool/pull/5

Let me know if it's.

Cheers

**Comment by eduardotd** [comment]
Thank you very much!
