### ISSUE TITLE
My simple pool implementation

### ISSUE THREAD

**Issue by bubnenkoff** [agilord/postgres_pool#8]
Hello, this request is not related with your lib, but you have enough experience and I hope that you will be able to review\check my code.

I wrote my own connection pool. And it's seems that it working, but I am not sure it's really do pooling, or it use only one connection. The code is next:
```
List<PostgreSQLConnection> connectionPool = [];

 class BasicConnectionPool {
    late String host;
    late int port;
    late String dbname;
    late String user;
    late String password;

    // late List<PostgreSQLConnection> connectionPool;
    List<PostgreSQLConnection> usedConnections =  [];
    static int INITIAL_POOL_SIZE = 10;

    BasicConnectionPool(String host, int port, String dbname, String user, String password);

    static Future<BasicConnectionPool> create(String host, int port, String dbname, String user, String password) async {
      // var pool = <PostgreSQLConnection>[];
      for (int i = 0; i < INITIAL_POOL_SIZE; i++) {
          var conn = createConnection(host, port, dbname, user, password);
          await conn.open();
          connectionPool.add(conn);
      }
      return  BasicConnectionPool(host, port, dbname, user, password);
    }
    
     PostgreSQLConnection getConnection() {
        var connection = connectionPool.removeLast();  //remove(connectionPool.size() - 1);
        usedConnections.add(connection);
        return connection;
    }
    
     bool releaseConnection(PostgreSQLConnection connection) {
        connectionPool.add(connection);
        return usedConnections.remove(connection);
    }
    
     static PostgreSQLConnection createConnection(String host, int port, String dbname, String user, String password) {
       return PostgreSQLConnection (host,  port, dbname, username: user, password: password);
     }

     int getSize() {
        return connectionPool.length + usedConnections.length;
    }

}
```

app:
```
late PostgreSQLConnection connection;
void main() async {

  var conPool = await BasicConnectionPool.create('localhost', 5432, 'db', 'postgres', '123');
  connection = conPool.getConnection();
  
  
  // handler that need pooling because a lot of requests
  Future<dynamic> commandFromParser(Map body) async {
      List<List<dynamic>> result = await connection.query(body['sql']).timeout(Duration(seconds: 120));
      return result;
    } on PostgreSQLException catch (e) {
        await connection.open();
    } on Exception catch (e) {
      print('commandFromParser exception on e: ${e}');
    }
  }  
```  

Could you look at this code please?

**Comment by isoos** [comment]
I think these things are hard to judge just by looking at the code. Ideally, you write some tests that drive the pool at edge cases, however that's a lot of work itself to design good tests for it. The second best thing is to log a lot, and use the pool in a highly concurrent application, observing the logs if it behaves like you want it to behave.

Curious: are you missing some feature from this pool?

**Comment by bubnenkoff** [comment]
I need something a really simple and tiny. Plus i need to improve my
skills. So i am trying to create my own bicycle.

Could you say please, am i right understand that my code is not use pool,
but simply take one connection from pool and use it?


Пн, 1 нояб. 2021 г. в 21:33, István Soós ***@***.***>:

**Comment by isoos** [comment]
> Could you say please, am i right understand that my code is not use pool, but simply take one connection from pool and use it?

I think the basic building blocks are there, but there are a few things that I'm not sure about, e.g. in your app, you do `await connection.open();` in an `catch` block, which doesn't really seem the proper way to do it.

A connection pool may be many things, e.g. you could create a fixed number of connections (e.g. 8), and the app will use up to 8 of them at maximum. You could initialize them on-demand, or initialize a fixed number upfront, and create new ones if needed.

The tricky part is blocking the app when the pool hits the configured limit (if you are using an upper bound for the number of connections, which is a good idea in most cases).  The `getConnection` method should be able to wait for a connection to free up, which usually means that is should return a `Future<connection>`. Also the user app should return the connection at the end of the block to free it up, which means usually a `try-finally` block, but it is also useful to distinguish between a clean execution and a bad state where the connection throw an IO error.

I've ended up with the current design after a lot of iterations. May not be the best design, I'm open for suggestions, but it seems to be covering a lot of edge cases :)

**Comment by bubnenkoff** [comment]
@isoos thanks for answer!
Be honestly API of your libs it's seems for me a little but too complex is this part:
```
    final f = pg.run((c) async {
      final rs = await c.query(
        'SELECT COUNT(*) FROM test_table WHERE type = @type',
        substitutionValues: {
          'type': i,
        },
      );
      return rs[0][0];
    });
```
I am about nesting. Is it possible to do it like:
`pg_pool.query()`
like I queries in single connections?

**Comment by isoos** [comment]
The pool in this package implements the postgres execution context interface, and wraps it with the `run`, you can call `query` directly:
https://github.com/agilord/postgres_pool/blob/master/lib/postgres_pool.dart#L565-L583
https://pub.dev/documentation/postgres_pool/latest/postgres_pool/PgPool/query.html

**Comment by bubnenkoff** [comment]
Thanks! It seems that I misunderstood some parts of your lib. 
Could you add to readme example of using classical connection and pg_pool connection? 

If I can call `query` directly what profit from nesting call?

**Comment by isoos** [comment]
> Could you add to readme example of using classical connection and pg_pool connection?

I'm open for PRs :)

> If I can call query directly what profit from nesting call?

You may have multiple queries and statements related to a single session, which you may want to execute on the single connection. I'm also considering to merge `run` and `runTx` in a future version, as they seem to be almost identical on the surface, except one also opens a transaction.
